language: cpp

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: clang
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
  - os: linux
    dist: trusty
    sudo: required
    env: GRADLE_ARGS='-Parm -Proborio'

addons:
  apt:
    packages:
      - g++-multilib
      - lib32stdc++6

before_install:
- wpi/ntcore/.travis-scripts/install.sh

script:
- "./gradlew clean build $GRADLE_ARGS"

notifications:
  email: false