language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - gcc-4.8-multilib
    - g++-4.8
    - g++-4.8-multilib
    - libc6-dev-i386
    - linux-libc-dev:i386
    - libstdc++-4.8
    - clang

compiler:
- clang
- gcc

os:
- linux
- osx

before_install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

install:
- "./gradlew build"

notifications:
  email: false