language: cpp

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    compiler: gcc
  - os: linux
    dist: trusty
    sudo: required
    env: GRADLE_ARGS='-Parm -Proborio' CUSTOM_CXX=arm-frc-linux-gnueabi-g++ ROBORIO=true

addons:
  apt:
    packages:
      - g++-multilib
      - lib32stdc++6

before_install:
- if [ -n "$CUSTOM_CXX" ]; then export CXX=$CUSTOM_CXX; fi
- wpi/ntcore/.travis-scripts/install.sh

install:
- if [ -n "$ROBORIO" ]; then ./gradlew :wpi:wpilib:build -Parm -Proborio; fi

script:
- "./gradlew clean build $GRADLE_ARGS"

notifications:
  email: false